In [100]:
import importlib
from tkinter.constants import RIGHT

import numpy as np
import assgn2025
importlib.reload(assgn2025)

from assgn2025 import (
    get_Householder,
    left_multiply,
    left_eliminate,
    right_multiply,
    right_eliminate,
    bidiagonalise,
    bidiagonal_svd,
    general_svd,
    lapack_bidiagonal_svd
)


In [101]:
# init matrix

# np.random.seed(41)

# set parameters
max_value = 20 # Maximum absolute value for entries in generated matrix/vector
max_size = 5 # max_size >= m >= n >= 1
m = np.random.randint(2, max_size)
n = np.random.randint(2, m + 1)
# m=4
# n=3

# init x
x = np.random.randint(-max_value, max_value + 1, size=(m, 1))
print(f"Generated x ({m}x{1}):\n", x)

# init A
def generate_full_rank_integer_matrix(m, n, max_value = 20):
    while True:
        A = np.random.randint(-max_value, max_value + 1, size=(m, n))
        if np.linalg.matrix_rank(A) == n:
            return A

A = generate_full_rank_integer_matrix(m, n)
print(f"Generated A ({m}x{n}):\n", A)


Generated x (4x1):
 [[10]
 [ 3]
 [-6]
 [ 5]]
Generated A (4x3):
 [[ 13   8  -4]
 [  6 -17  18]
 [-15   3  16]
 [ -5 -16 -10]]


In [102]:
# q2

k = 0
v, tau = get_Householder(x, k)
print("\nv =\n", v)
print("\ntau =\n", tau)

# H = I - tau * v v^T
H = np.eye(m) - tau * (v @ v.T)
print("\nH =\n",H)

# y = H x
y = H @ x
print("\ny = H x = \n", y)

# 1. H @ H
H_squared = H @ H
# print("\nH @ H =\n", H_squared)

# 2. H.T @ y
Hy = H.T @ y
# print("\nHy =\n",Hy)

# 3. ||x|| , ||y||
x_norm = np.linalg.norm(x)
y_norm = np.linalg.norm(y)
# print("\nx_norm =\n", x_norm)
# print("\ny_norm =\n", y_norm)

# 4. y[k+1:m] 
y_kplus1_to_m = y[k+1:]
# print("\ny[k+1:m] =\n", y_kplus1_to_m)

# 5. Check results
print("\n============================================================\n")
print("\n[Q2][1] H @ H ≈ I:")
print("\nH @ H =\n", H_squared)
print("\nI      =\n", np.eye(m))
print("\nH @ H ≈ I:", np.allclose(H_squared, np.eye(m)))

print("\n============================================================\n")
print("\n[Q2][2] x ≈ H.T @ y:")
print("\nx        =\n", x)
print("\nH.T @ y  =\n", Hy)
print("\nx ≈ H.T @ y:", np.allclose(x, Hy))

print("\n============================================================\n")
print("\n[Q2][3] ||x|| ≈ ||y||:")
print("\n||x|| =", x_norm)
print("\n||y|| =", y_norm)
print("\n||x|| ≈ ||y||:", np.allclose(x_norm, y_norm))

print("\n============================================================\n")
print("\n[Q2][4] y[k+1:m] ≈ 0:")
print("\ny[k+1:m] =\n", y_kplus1_to_m)
print("\ny[k+1:m] ≈ 0:", np.allclose(y[k+1:], 0))
print("\n============================================================\n")






v =
 [[ 1.        ]
 [ 0.13021735]
 [-0.2604347 ]
 [ 0.21702892]]

tau =
 1.7669649888473706

H =
 [[-0.76696499 -0.2300895   0.46017899 -0.38348249]
 [-0.2300895   0.97003836  0.05992329 -0.04993607]
 [ 0.46017899  0.05992329  0.88015342  0.09987215]
 [-0.38348249 -0.04993607  0.09987215  0.91677321]]

y = H x = 
 [[-1.30384048e+01]
 [-4.44089210e-16]
 [ 8.88178420e-16]
 [-8.88178420e-16]]



[Q2][1] H @ H ≈ I:

H @ H =
 [[ 1.00000000e+00  5.55111512e-17 -1.17961196e-16  1.11022302e-16]
 [ 5.55111512e-17  1.00000000e+00 -6.93889390e-18  1.38777878e-17]
 [-1.17961196e-16 -6.93889390e-18  1.00000000e+00 -1.38777878e-17]
 [ 1.11022302e-16  1.38777878e-17 -1.38777878e-17  1.00000000e+00]]

I      =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

H @ H ≈ I: True



[Q2][2] x ≈ H.T @ y:

x        =
 [[10]
 [ 3]
 [-6]
 [ 5]]

H.T @ y  =
 [[10.]
 [ 3.]
 [-6.]
 [ 5.]]

x ≈ H.T @ y: True



[Q2][3] ||x|| ≈ ||y||:

||x|| = 13.038404810405298

||y|| = 13.0384048104053

||x|| ≈ ||y

In [103]:
# q4

x = A[:, [0]].copy()  # make it a column vector
k = 0  

HA = A.copy()
for j in range(n):
    k = j 
    x = HA[:, [j]].copy()
    v, tau = get_Householder(x, k)
    H = np.eye(m) - tau * (v @ v.T)
    HA = H @ HA
    
# Q, R = np.linalg.qr(A)
# print("\nR =\n", R)


    
A1 = A.copy()
A2 = A.copy()
for j in range(n):
    k = j
    x = A1[:, [j]].copy()
    v, tau = get_Householder(x, k)
    A1= left_multiply(k, v, tau, A1.copy())
    
for j in range(n):
    k = j
    x = A2[:, [j]].copy()
    v, tau = get_Householder(x, k)
    A2 = left_eliminate(k, v, tau, A2.copy())

# Compare results
print("\n============================================================\n")
print("[Q4] HA ?≈ left_multiply ?≈ left_eliminate:")
print("\nHA =\n", HA)
print("\nleft_multiply =\n", A1)
print("\nleft_eliminate =\n", A2)
print("\nHA ?≈ left_multiply ?≈ left_eliminate:", np.allclose(HA, A1) and np.allclose(HA, A2))

print("\n============================================================\n")



[Q4] HA ?≈ left_multiply ?≈ left_eliminate:

HA =
 [[-2.13307290e+01 -1.73458675e+00  6.28201689e+00]
 [ 1.40380838e-15  2.47990163e+01 -4.80274279e+00]
 [-2.18481050e-15 -1.39472797e-15 -2.51688284e+01]
 [ 2.24669175e-15 -1.49619611e-15  1.79737276e-15]]

left_multiply =
 [[-2.13307290e+01 -1.73458675e+00  6.28201689e+00]
 [ 0.00000000e+00  2.47990163e+01 -4.80274279e+00]
 [ 0.00000000e+00  2.49514255e-15 -2.51688284e+01]
 [ 0.00000000e+00 -2.91806307e-16  3.55271368e-15]]

left_eliminate =
 [[-2.13307290e+01 -1.73458675e+00  6.28201689e+00]
 [ 0.00000000e+00  2.47990163e+01 -4.80274279e+00]
 [ 0.00000000e+00 -1.77635684e-15 -2.51688284e+01]
 [ 0.00000000e+00  1.77635684e-15  3.55271368e-15]]

HA ?≈ left_multiply ?≈ left_eliminate: True




In [104]:
# q6

AH = HA.copy()
print("\nAH =\n", AH)

for k in range(n-1):
    x = AH[[k], :].T.copy()  # 第 i 行 → 列向量
    v, tau = get_Householder(x, k+1)
    # print("\nv =\n", v)
    H = np.eye(n) - tau * (v @ v.T)
    AH = AH @ H 
    # print("\nAH =\n", AH)

# 用 single-row 右乘函数，循环模拟 AH 整体行为
A1 = HA.copy()
A2 = HA.copy()
for k in range(n-1):
    x = A1[[k], :].T.copy()
    v, tau = get_Householder(x, k+1)
    A1 = right_multiply(k, v, tau, A1)
    
    
for k in range(n-1):
    x = A2[[k], :].T.copy()
    v, tau = get_Householder(x, k+1)
    A2 = right_eliminate(k, v, tau, A2)

# Compare results
print("\n============================================================\n")
print("[Q6] AH ?≈ right_multiply ?≈ right_eliminate:")
print("\nAH =\n", AH)
print("\nright_multiply =\n", A1)
print("\nright_eliminate =\n", A2)
print("\nAH ?≈ right_multiply ?≈ right_eliminate:", np.allclose(AH, A1) and np.allclose(AH, A2))

print("\n============================================================\n")


AH =
 [[-2.13307290e+01 -1.73458675e+00  6.28201689e+00]
 [ 1.40380838e-15  2.47990163e+01 -4.80274279e+00]
 [-2.18481050e-15 -1.39472797e-15 -2.51688284e+01]
 [ 2.24669175e-15 -1.49619611e-15  1.79737276e-15]]


[Q6] AH ?≈ right_multiply ?≈ right_eliminate:

AH =
 [[-2.13307290e+01  6.51709502e+00 -5.18226526e-16]
 [ 1.40380838e-15 -1.12299969e+01 -2.26261954e+01]
 [-2.18481050e-15 -2.42609637e+01  6.69892281e+00]
 [ 2.24669175e-15  2.13076654e-15  9.63838987e-16]]

right_multiply =
 [[-2.13307290e+01  6.51709502e+00  0.00000000e+00]
 [ 1.40380838e-15 -1.12299969e+01 -2.26261954e+01]
 [-2.18481050e-15 -2.42609637e+01  6.69892281e+00]
 [ 2.24669175e-15  2.13076654e-15  9.63838987e-16]]

right_eliminate =
 [[-2.13307290e+01  6.51709502e+00  0.00000000e+00]
 [ 1.40380838e-15 -1.12299969e+01 -2.26261954e+01]
 [-2.18481050e-15 -2.42609637e+01  6.69892281e+00]
 [ 2.24669175e-15  2.13076654e-15  9.63838987e-16]]

AH ?≈ right_multiply ?≈ right_eliminate: True




In [105]:
#  Q8
# P(mxm) B(mxn) QT(nxn)
P, B, QT = bidiagonalise(A)

print("\n============================================================")
print("[Q8]")
print("\nP =\n", P)
print("\nB =\n", B)
print("\nQT =\n", QT)
print("\n============================================================")


# 1. reconstruction of A:
# check A ?= P B QT
print("\n[Q8][1]Check whether A ≈ P @ B @ QT\n")

A_hat = P @ B @ QT
print("A_hat = P @ B @ QT = \n", A_hat)
print("\nA_hat ?= A :", np.allclose(A_hat, A))
print("\n============================================================\n")

# 2. check the orthogonality of P and Q
print("[Q8][2]check the orthogonality of P and Q")

PT_P = P.T @ P
print("\nPT_P =\n", PT_P)
print("\nPT_P ?= I :", np.allclose(PT_P, np.eye(m)))

QT_Q = QT @ QT.T
print("\nQT_Q =\n", QT_Q)
print("\nQT_Q ?= I :", np.allclose(QT_Q, np.eye(n)))
print("\n============================================================\n")

# 3. check whether B is upper bidiagonal
print("[Q8][3]check whether B is upper bidiagonal")
print("\nDefinition: bij = 0 unless j ∈ {i, i + 1}\n")

def is_upper_bidiagonal(B, tol=1e-6):
    m, n = B.shape
    for i in range(m):
        for j in range(n):
            if j != i and j != i+1 and abs(B[i, j]) > tol:
                return False
    return True


print("Is B upper bidiagonal? :", is_upper_bidiagonal(B))
print("\n============================================================\n")



[Q8]

P =
 [[-0.6094494   0.07530305 -0.27364676  0.7402826 ]
 [-0.28128434 -0.88683262  0.36656883 -0.00585857]
 [ 0.70321085 -0.37560749 -0.36136684  0.48355716]
 [ 0.23440362  0.25841126  0.81250154  0.467033  ]]

B =
 [[-2.13307290e+01  6.51709502e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.67340081e+01 -3.42521704e+00]
 [ 0.00000000e+00  1.77635684e-15  2.33471234e+01]
 [ 0.00000000e+00 -2.66453526e-15  3.55271368e-15]]

QT =
 [[ 1.         0.         0.       ]
 [ 0.        -0.2661595  0.963929 ]
 [ 0.        -0.963929  -0.2661595]]


[Q8][1]Check whether A ≈ P @ B @ QT

A_hat = P @ B @ QT = 
 [[ 13.   8.  -4.]
 [  6. -17.  18.]
 [-15.   3.  16.]
 [ -5. -16. -10.]]

A_hat ?= A : True


[Q8][2]check the orthogonality of P and Q

PT_P =
 [[ 1.00000000e+00 -5.55111512e-17 -1.38777878e-17 -1.11022302e-16]
 [-5.55111512e-17  1.00000000e+00  2.77555756e-17  2.77555756e-17]
 [-1.38777878e-17  2.77555756e-17  1.00000000e+00 -5.55111512e-17]
 [-1.11022302e-16  2.77555756e-17 -5.55111512e-1

In [106]:
# Q9
P, B, QT = bidiagonalise(A)


# 对B进行SVD
Utilde, sigma, VTtilde = bidiagonal_svd(B)

# 1. reconstruction of B:
# check B ?= Utilde @ sigma @ VTtilde
print("\n[Q9][1]check B ?= Utilde @ sigma @ VTtilde\n")

B_hat = Utilde @ np.diag(sigma) @ VTtilde
print("B =\n", B)
print("\nB_hat = Utilde @ sigma @ VTtilde = \n", B_hat)
print("\nB_hat ?= B :", np.allclose(B_hat, B))
print("\n============================================================\n")

# 2. check the orthogonality of Utilde and VTtilde
print("[Q9][2]check the orthogonality of Utilde and VTtilde")

UtildeT_Utilde = Utilde.T @ Utilde
print("\nUtildeT_Utilde =\n", UtildeT_Utilde)
print("\nUtildeT_Utilde ?= I :", np.allclose(UtildeT_Utilde, np.eye(n)))

VTtildeT_VTtilde = VTtilde.T @ VTtilde
print("\nVTtildeT_VTtilde =\n", VTtildeT_VTtilde)
print("\nVTtildeT_VTtilde ?= I :", np.allclose(VTtildeT_VTtilde, np.eye(n)))
print("\n============================================================\n")

# 3. check that sigma is sorted in descending order
print("[Q9][3] check that sigma is sorted in descending order")

is_sorted = np.all(sigma[:-1] >= sigma[1:])
print("sigma =", sigma)
print("Is sigma sorted descending? :", is_sorted)
print("\n============================================================\n")

# 4. compare with numpy.linalg.svd
print("[Q9][4] compare singular values with NumPy's SVD")

_, sigma_np, _ = np.linalg.svd(B, full_matrices=False)
print("sigma (our SVD)     =", sigma)
print("sigma (NumPy SVD)   =", sigma_np)
print("Match with NumPy?   :", np.allclose(np.sort(sigma)[::-1], sigma_np))
print("\n============================================================\n")


[Q9][1]check B ?= Utilde @ sigma @ VTtilde

B =
 [[-2.13307290e+01  6.51709502e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.67340081e+01 -3.42521704e+00]
 [ 0.00000000e+00  1.77635684e-15  2.33471234e+01]
 [ 0.00000000e+00 -2.66453526e-15  3.55271368e-15]]

B_hat = Utilde @ sigma @ VTtilde = 
 [[-2.13307290e+01  6.51709502e+00 -1.63381559e-15]
 [-2.81146854e-15 -2.67340081e+01 -3.42521704e+00]
 [ 1.15530701e-15  4.92048986e-15  2.33471234e+01]
 [ 3.79558280e-32 -2.66453526e-15  3.55271368e-15]]

B_hat ?= B : True


[Q9][2]check the orthogonality of Utilde and VTtilde

UtildeT_Utilde =
 [[1.00000000e+00 2.08166817e-16 2.22044605e-16]
 [2.08166817e-16 1.00000000e+00 3.95634432e-16]
 [2.22044605e-16 3.95634432e-16 1.00000000e+00]]

UtildeT_Utilde ?= I : True

VTtildeT_VTtilde =
 [[1.00000000e+00 1.04083409e-16 5.55111512e-17]
 [1.04083409e-16 1.00000000e+00 1.10839463e-16]
 [5.55111512e-17 1.10839463e-16 1.00000000e+00]]

VTtildeT_VTtilde ?= I : True


[Q9][3] check that sigma is sorted in 

In [107]:
# Q11
# 调用 general_svd
U, sigma, VT = general_svd(A)

# 重构矩阵 A ≈ U Σ V^T
Sigma = np.diag(sigma)
A_hat = U @ Sigma @ VT

# 验证是否还原
print("U =\n", U)
print("sigma =", sigma)
print("VT =\n", VT)
print("重构误差 = ", np.linalg.norm(A - A_hat))  # 应该非常接近0

U =
 [[-0.39982205 -0.04108073  0.53892149]
 [ 0.72896403  0.3683942   0.57694266]
 [ 0.55090689 -0.60949411 -0.30197848]
 [ 0.07249385  0.70079599 -0.53433117]]
sigma = [28.94066066 23.19985689 19.82939234]
VT =
 [[-0.32652935 -0.5216932   0.7881718 ]
 [ 0.31529278 -0.84623649 -0.42950468]
 [ 0.89104941  0.10825899  0.44080715]]
重构误差 =  1.79897244661201e-14


In [108]:
# q12
# 方法一：使用 general_svd（通过 bidiagonal_svd）
U1, sigma1, VT1 = general_svd(A)

# 方法二：使用 lapack_bidiagonal_svd（通过 LAPACK Francis 算法）
P, B, QT = bidiagonalise(A)
U2, sigma2, VT2 = lapack_bidiagonal_svd(P, B, QT)

# 生成对角矩阵 Σ
Sigma1 = np.diag(sigma1)
Sigma2 = np.diag(sigma2)

# 重构矩阵
A1_hat = U1 @ Sigma1 @ VT1
A2_hat = U2 @ Sigma2 @ VT2

# 计算重构误差和奇异值误差
recon_error_1 = np.linalg.norm(A - A1_hat)
recon_error_2 = np.linalg.norm(A - A2_hat)
singular_diff = np.linalg.norm(sigma1 - sigma2)


# 打印比较结果
print("【方法一】general_svd 重构误差：", np.linalg.norm(A - A1_hat))
print("【方法二】lapack_bidiagonal_svd 重构误差：", np.linalg.norm(A - A2_hat))
print("奇异值是否一致（σ）:", np.allclose(sigma1, sigma2, atol=1e-10))
print("两个方法的重构结果是否一致:", np.allclose(A1_hat, A2_hat, atol=1e-10))

【方法一】general_svd 重构误差： 1.79897244661201e-14
【方法二】lapack_bidiagonal_svd 重构误差： 2.631767229038405e-14
奇异值是否一致（σ）: True
两个方法的重构结果是否一致: True
